package com.bussiness.dao;

import com.bussiness.pojo.Cart;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    int insert(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    Cart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    List<Cart> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Cart record);

    /*
     * 根据用户id和商品id查询购物车信息
     */
    Cart findCartByUseridAndProductId(@Param("userid") Integer userId, @Param("productid") Integer productId);

    /*
     * 查询用户的购物车信息
     */
    List<Cart> findCartsByUserid(@Param("userid") Integer userid);

    /*
     * 统计用户购物车中未选中的商品数量
     */
    Integer isAllChecked(@Param("userid") Integer userid);

    /*
     * 查看购物车中用户勾选的商品
     */
    List<Cart> findCartsByUseridAndChecked(@Param("userId") Integer userId);

    /*
     * 清空购物车中已选中商品
     */
    int deleteBatch(@Param("cartList") List<Cart> cartList);
}